version: '3'
services:
  andrec:
    build: .
    ports:
      - 56000:8080
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
  bash:
    build: .
    volumes:
      - ./app:/app
